# Generated by Django 4.1.1 on 2022-10-07 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="ReviewId",
            new_name="review_id",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="Body",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="Stars",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="Title",
        ),
        migrations.AddField(
            model_name="reviews",
            name="body",
            field=models.TextField(
                default="Insert Your Text Here.", editable=False, max_length=200
            ),
        ),
        migrations.AddField(
            model_name="reviews",
            name="stars",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="reviews",
            name="title",
            field=models.CharField(
                default="Insert Your Title Here.", editable=False, max_length=50
            ),
        ),
    ]
