# Generated by Django 4.1.1 on 2022-10-08 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("housingInfo", "0004_alter_housinginfo_housing_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0002_rename_reviewid_reviews_review_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="housing_info",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="housingInfo.housinginfo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviews",
            name="user_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reviews",
            name="body",
            field=models.TextField(default="Insert Your Text Here.", max_length=200),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="title",
            field=models.CharField(default="Insert Your Title Here.", max_length=50),
        ),
    ]
