# Generated by Django 4.1.1 on 2022-10-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_reviews_housing_info_reviews_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="user_id",
        ),
    ]
