# Generated by Django 4.1.1 on 2022-10-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("housingInfo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="housinginfo",
            old_name="HousingId",
            new_name="housing_id",
        ),
        migrations.RenameField(
            model_name="housinginfo",
            old_name="HousingName",
            new_name="housing_name",
        ),
        migrations.RenameField(
            model_name="housinginfo",
            old_name="HousingType",
            new_name="housing_type",
        ),
        migrations.RenameField(
            model_name="housinginfo",
            old_name="ImageFileName",
            new_name="image_filename",
        ),
    ]
