# Generated by Django 4.1.1 on 2022-10-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housingInfo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="housinginfo",
            old_name="HousingId",
            new_name="housing_id",
        ),
        migrations.RenameField(
            model_name="housinginfo",
            old_name="HousingType",
            new_name="housing_type",
        ),
        migrations.RenameField(
            model_name="housinginfo",
            old_name="HousingName",
            new_name="image_filename",
        ),
        migrations.RemoveField(
            model_name="housinginfo",
            name="ImageFileName",
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="housing_name",
            field=models.CharField(default="", editable=False, max_length=500),
        ),
    ]
