# Generated by Django 4.1.1 on 2022-10-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housingInfo", "0002_rename_housingid_housinginfo_housing_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housinginfo",
            name="housing_name",
            field=models.CharField(default="tem", editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name="housinginfo",
            name="housing_type",
            field=models.CharField(max_length=50),
        ),
    ]
