# Generated by Django 4.1.1 on 2022-10-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housingInfo", "0003_alter_housinginfo_housing_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housinginfo",
            name="housing_name",
            field=models.CharField(default="", max_length=500),
        ),
    ]
