# Generated by Django 4.1.1 on 2022-10-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housingInfo", "0004_alter_housinginfo_housing_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housinginfo",
            name="image_filename",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
