# Generated by Django 4.1.1 on 2022-10-28 19:09

import apps.housingInfo.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("housingInfo", "0006_alter_housinginfo_image_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(max_length=100)),
                ("street_address_two", models.CharField(max_length=100)),
                ("country", models.CharField(default="United States", max_length=50)),
                (
                    "zip",
                    models.IntegerField(
                        validators=[apps.housingInfo.models.validate_zipcode]
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="housinginfo",
            name="housing_type",
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="housing_description",
            field=models.CharField(
                default="This is where the description goes!", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="housing_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="housing_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("1B", "1 Bedroom"),
                        ("2B", "2 Bedroom"),
                        ("3B", "3 Bedroom"),
                        ("4B", "4 Bedroom"),
                        ("5B", "5 or More Bedroom"),
                        ("1S", "Studio"),
                    ],
                    max_length=2,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="housing_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="housingInfo.address",
            ),
        ),
    ]
