# Generated by Django 4.1.1 on 2022-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housingInfo", "0007_address_remove_housinginfo_housing_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(default="Champaign", max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="state",
            field=models.CharField(default="Illinois", max_length=100),
        ),
    ]
