# Generated by Django 4.1.1 on 2022-11-01 21:40

import apps.housingInfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housingInfo", "0008_address_city_address_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="housinginfo",
            name="housing_location",
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="city",
            field=models.CharField(default="Champaign", max_length=100),
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="country",
            field=models.CharField(default="United States", max_length=50),
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="state",
            field=models.CharField(default="Illinois", max_length=100),
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="street_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="street_address_two",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="housinginfo",
            name="zip",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[apps.housingInfo.models.validate_zipcode],
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
