# Generated by Django 4.1.1 on 2022-11-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "housingInfo",
            "0009_remove_housinginfo_housing_location_housinginfo_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="housinginfo",
            name="housing_description",
            field=models.CharField(
                default="This is where the description goes!", max_length=5000
            ),
        ),
    ]
